import { ClaimState } from './types';

export const CLAIM_STATE_LABELS: Record<ClaimState, string> = {
  DRAFT: 'Draft',
  FNOL_SUBMITTED: 'Claim Submitted',
  VEHICLE_VERIFIED: 'Vehicle Verified',
  ERP_CREATED: 'ERP Claim Created',
  ASSIGNED: 'Assigned to Agent',
  INVESTIGATION_IN_PROGRESS: 'Investigation In Progress',
  INFO_REQUESTED: 'More Information Requested',
  INFO_RECEIVED: 'Information Received',
  ESTIMATE_PENDING: 'Assessment Pending',
  ESTIMATE_SUBMITTED: 'Assessment Submitted',
  APPROVAL_PENDING: 'Approval Pending',
  APPROVED: 'Approved',
  PARTIALLY_APPROVED: 'Partially Approved',
  REJECTED: 'Rejected',
  REPAIR_IN_PROGRESS: 'Repair In Progress',
  REPAIR_COMPLETED: 'Repair Completed',
  SETTLEMENT_PREPARED: 'Settlement Prepared',
  PAYMENT_IN_PROGRESS: 'Payment In Progress',
  PAID: 'Paid',
  CLOSED: 'Closed',
};

export const CLAIM_TRANSITIONS: Record<ClaimState, ClaimState[]> = {
  DRAFT: ['FNOL_SUBMITTED'],
  FNOL_SUBMITTED: ['VEHICLE_VERIFIED', 'INFO_REQUESTED'],
  VEHICLE_VERIFIED: ['ERP_CREATED', 'INFO_REQUESTED'],
  ERP_CREATED: ['ASSIGNED'],
  ASSIGNED: ['INVESTIGATION_IN_PROGRESS', 'INFO_REQUESTED'],
  INVESTIGATION_IN_PROGRESS: ['ESTIMATE_PENDING', 'INFO_REQUESTED'],
  INFO_REQUESTED: ['INFO_RECEIVED', 'REJECTED'],
  INFO_RECEIVED: ['INVESTIGATION_IN_PROGRESS', 'ESTIMATE_PENDING'],
  ESTIMATE_PENDING: ['ESTIMATE_SUBMITTED', 'INFO_REQUESTED'],
  ESTIMATE_SUBMITTED: ['APPROVAL_PENDING', 'INFO_REQUESTED'],
  APPROVAL_PENDING: ['APPROVED', 'PARTIALLY_APPROVED', 'REJECTED'],
  APPROVED: ['REPAIR_IN_PROGRESS', 'SETTLEMENT_PREPARED'],
  PARTIALLY_APPROVED: ['REPAIR_IN_PROGRESS', 'SETTLEMENT_PREPARED'],
  REJECTED: ['CLOSED', 'INFO_REQUESTED'],
  REPAIR_IN_PROGRESS: ['REPAIR_COMPLETED', 'INFO_REQUESTED'],
  REPAIR_COMPLETED: ['SETTLEMENT_PREPARED'],
  SETTLEMENT_PREPARED: ['PAYMENT_IN_PROGRESS'],
  PAYMENT_IN_PROGRESS: ['PAID', 'INFO_REQUESTED'],
  PAID: ['CLOSED'],
  CLOSED: [],
};

export function canTransition(from: ClaimState, to: ClaimState): boolean {
  return CLAIM_TRANSITIONS[from].includes(to);
}
